name: "Integration Testing"

on: [push]

jobs:
  multi-language-repo_test-autodetect-languages:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Move codeql-action
      shell: bash
      run: |
        mkdir ../action
        shopt -s dotglob
        mv * ../action/
        mv ../action/tests/multi-language-repo/* .
    - uses: ./../action/init
    - name: Build code
      shell: bash
      run: ./build.sh
    - uses: ./../action/analyze
      env:
        TEST_MODE: true

  multi-language-repo_test-custom-queries:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Move codeql-action
      shell: bash
      run: |
        mkdir ../action
        shopt -s dotglob
        mv * ../action/
        mv ../action/tests/multi-language-repo/* .
    - uses: ./../action/init
      with:
        languages: cpp,csharp,go,java,javascript,python
        config-file: ./.github/codeql/custom-queries.yml
    - name: Build code
      shell: bash
      run: ./build.sh
    - uses: ./../action/analyze
      env:
        TEST_MODE: true


  multi-language-repo_rubocop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Move codeql-action
      shell: bash
      run: |
        mkdir ../action
        shopt -s dotglob
        mv * ../action/
        mv ../action/tests/multi-language-repo/* .
    - uses: arthurnn/code-scanning-rubocop/rubocop-action@master
    - uses: ./../action/upload-sarif
      with:
        sarif_file: rubocop.sarif
      env:
        TEST_MODE: true